version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5050:5432
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gfhjkm7757
      - POSTGRES_DB=ChirkV2
    command: ["postgres","-c","wal_level=logical"]
    volumes:
      - ./chirkdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - HOST=database

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "$UID:$GID"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3001:3001
    volumes:
      - grafana-data:/var/lib/grafana
      - ./:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=3001
      - GF_AUTH_ANONYMOUS_ENABLED=true


volumes:
  db-data:
  prometheus-data:
  grafana-data:

networks:
  chirknetwork: